name: Build

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    container: debian:bookworm-slim

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: ./.github/actions/setup-toolchain
        with:
          arch: ${{ matrix.arch }}

      - name: "CMake: Configure"
        run: |
          cmake -G Ninja -B build/${{ matrix.arch }} -DARCH=${{ matrix.arch }} -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}

      - name: "CMake: Build"
        run: |
          cmake --build build/${{ matrix.arch }}

      - name: "CMake: Package"
        run: |
          cmake --build build/${{ matrix.arch }} --target package

      - name: "Archive packages"
        uses: actions/upload-artifact@v4
        with:
          name: packages_${{ matrix.arch }}
          path: |
            build/${{ matrix.arch }}/*.deb
            build/${{ matrix.arch }}/*.tar.gz
            build/${{ matrix.arch }}/latest
          retention-days: 1
