name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Install gcovr
        run: |
          sudo apt-get update && sudo apt-get -y install gcovr
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: "CMake: Configure"
        run: |
          cmake -G Ninja -B build/test -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFLECS_BUILD_TESTS=On -DCMAKE_INSTALL_PREFIX=out/test
      - name: "CMake: Build"
        run: |
          docker network inspect bridge --format '{{(index .IPAM.Config 0).Gateway}}'
          cmake --build build/test
      - name: "CMake: Test"
        run: |
          ctest --test-dir build/test --verbose
      - name: "CMake: Coverage"
        run: |
          cmake --build build/test --target coverage
